name: main

on:
  push:
    branches: [$default-branch]

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  test-e2e:
    name: E2E tests
    needs: [build]
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome86-ff82

    env:
      app_host: 'http://localhost:3000'
      # pass the Dashboard record key as an environment variable
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      # pass GitHub token to allow accurately detecting a build vs a re-run build
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        cwd: [angularjs-ng-file-upload, react-dropzone, react-html5-input, shadow-dom-native]

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - name: Install dependencies and verify Cypress
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./recipes/${{ matrix.cwd }}
          runTests: false
      - name: Run web application
        run: npm start & # & helps to run daemonized app
        working-directory: ./recipes/${{ matrix.cwd }}
      - name: Run Chrome tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./recipes/${{ matrix.cwd }}
          install: false
          record: true
          group: '${{ matrix.cwd }}/Chrome'
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
          browser: chrome
          headless: false
          wait-on: ${{ env.app_host }}
      - name: Run Chrome headless tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./recipes/${{ matrix.cwd }}
          install: false
          record: true
          group: '${{ matrix.cwd }}/Chrome (headless)'
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
          browser: chrome
          headless: true
          wait-on: ${{ env.app_host }}
      # - name: Run Firefox tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     working-directory: ./recipes/${{ matrix.cwd }}
      #     install: false
      #     record: true
      #     group: '${{ matrix.cwd }}/Firefox'
      #     ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
      #     browser: firefox
      #     headless: false
      #     wait-on: ${{ env.app_host }}
      # - name: Run Firefox headless tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     working-directory: ./recipes/${{ matrix.cwd }}
      #     install: false
      #     record: true
      #     group: '${{ matrix.cwd }}/Firefox (headless)'
      #     ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
      #     browser: firefox
      #     headless: true
      #     wait-on: ${{ env.app_host }}
      - name: Run Electron tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./recipes/${{ matrix.cwd }}
          install: false
          record: true
          group: '${{ matrix.cwd }}/Electron'
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
          browser: electron
          headless: false
          wait-on: ${{ env.app_host }}
      - name: Run Electron headless tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./recipes/${{ matrix.cwd }}
          install: false
          record: true
          group: '${{ matrix.cwd }}/Electron (headless)'
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
          browser: electron
          headless: true
          wait-on: ${{ env.app_host }}
